/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ApSpinner {
    }
    interface ApStockFinder {
    }
    interface ApStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLApSpinnerElement extends Components.ApSpinner, HTMLStencilElement {
    }
    var HTMLApSpinnerElement: {
        prototype: HTMLApSpinnerElement;
        new (): HTMLApSpinnerElement;
    };
    interface HTMLApStockFinderElement extends Components.ApStockFinder, HTMLStencilElement {
    }
    var HTMLApStockFinderElement: {
        prototype: HTMLApStockFinderElement;
        new (): HTMLApStockFinderElement;
    };
    interface HTMLApStockPriceElement extends Components.ApStockPrice, HTMLStencilElement {
    }
    var HTMLApStockPriceElement: {
        prototype: HTMLApStockPriceElement;
        new (): HTMLApStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "ap-spinner": HTMLApSpinnerElement;
        "ap-stock-finder": HTMLApStockFinderElement;
        "ap-stock-price": HTMLApStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface ApSpinner {
    }
    interface ApStockFinder {
        "onApStockClick"?: (event: CustomEvent<string>) => void;
    }
    interface ApStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "ap-spinner": ApSpinner;
        "ap-stock-finder": ApStockFinder;
        "ap-stock-price": ApStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ap-spinner": LocalJSX.ApSpinner & JSXBase.HTMLAttributes<HTMLApSpinnerElement>;
            "ap-stock-finder": LocalJSX.ApStockFinder & JSXBase.HTMLAttributes<HTMLApStockFinderElement>;
            "ap-stock-price": LocalJSX.ApStockPrice & JSXBase.HTMLAttributes<HTMLApStockPriceElement>;
        }
    }
}
